# docker-compose.yml
version: '3'
services:
  web:
    env_file:
      - .env
    build:
      context: .
      dockerfile: Dockerfile.dev
    #command: bundle exec rails s -p ${PORT} -b '0.0.0.0'
    command: sh -c "cd $SERVE_DIR && bundle exec jekyll serve --port $PORT --host 0.0.0.0 -w -c config publish/jekyll/_config.yml"
    volumes:
      - ./multisite:/app
      - ./bundler_gems:/usr/local/bundle/
    ports:
      - ${PORT}:${PORT}
  
