# Dockerfile.dev
FROM ruby:2.6-alpine as builder

RUN apk add --no-cache \
    build-base \
    busybox \
    ca-certificates \
    curl \
    git \
    gnupg1 \
    graphicsmagick \
    libffi-dev \
    libsodium-dev \
    nodejs \
    openssh-client \
    postgresql-dev \
    rsync \
    yarn

RUN mkdir -p /app
WORKDIR /app

#CMD ["bundle", "exec", "rails", "server", "-b", "0.0.0.0"]