# docker-compose.yml
version: '3'
services:
  web:
    env_file:
      - .env.dev
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./myapp:/myapp
      - ./bundler_gems:/usr/local/bundle/
    ports:
      - "3000:3000"
  
